const graph_rev = {
  edges: [
    { source: "patent", target: "organization", edge_type: "is_assignee_of" },
    {
      source: "target",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "disease",
      target: "organization",
      edge_type: "is_associated_with",
    },
    { source: "disease", target: "organization", edge_type: "is_parent_of" },
    {
      source: "scientific_concept",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "compound",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "vaccine",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "person", target: "organization", edge_type: "is_executive_in" },
    { source: "person", target: "organization", edge_type: "attended" },
    { source: "person", target: "organization", edge_type: "is_founder_of" },
    { source: "person", target: "organization", edge_type: "is_advisor_in" },
    { source: "person", target: "organization", edge_type: "is_employee_in" },
    {
      source: "person",
      target: "organization",
      edge_type: "is_board_member_in",
    },
    {
      source: "patent",
      target: "patent",
      edge_type: "is_application_parent_of",
    },
    { source: "disease", target: "patent", edge_type: "is_mentioned_in" },
    { source: "organization", target: "patent", edge_type: "is_assignee_of" },
    {
      source: "scientific_concept",
      target: "patent",
      edge_type: "is_mentioned_in",
    },
    { source: "compound", target: "patent", edge_type: "is_mentioned_in" },
    { source: "target", target: "patent", edge_type: "is_mentioned_in" },
    { source: "vaccine", target: "patent", edge_type: "is_mentioned_in" },
    { source: "organization", target: "patent", edge_type: "is_assignee_of" },
    { source: "person", target: "patent", edge_type: "is_inventor_of" },
    { source: "organization", target: "patent", edge_type: "is_assignee_of" },
    {
      source: "scientific_paper",
      target: "disease",
      edge_type: "is_mentioned_in",
    },
    { source: "disease", target: "disease", edge_type: "is_parent_of" },
    {
      source: "organization",
      target: "disease",
      edge_type: "is_associated_with",
    },
    { source: "organization", target: "disease", edge_type: "is_parent_of" },
    {
      source: "organization",
      target: "disease",
      edge_type: "is_associated_with",
    },
    { source: "organization", target: "disease", edge_type: "is_parent_of" },
    {
      source: "organization",
      target: "disease",
      edge_type: "is_associated_with",
    },
    { source: "organization", target: "disease", edge_type: "is_parent_of" },
    {
      source: "organization",
      target: "disease",
      edge_type: "is_associated_with",
    },
    { source: "organization", target: "disease", edge_type: "is_parent_of" },
    { source: "compound", target: "disease", edge_type: "has_effect_on" },
    { source: "target", target: "disease", edge_type: "is_associated_with" },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_sub_organization_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "organization", target: "organization", edge_type: "acquired" },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_sub_organization_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "organization", target: "organization", edge_type: "acquired" },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_sub_organization_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "organization", target: "organization", edge_type: "acquired" },
    { source: "funding_round", target: "organization", edge_type: "raised" },
    {
      source: "funding_round",
      target: "organization",
      edge_type: "participated_in",
    },
    {
      source: "vaccine",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "compound",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "scientific_concept",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "target",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "person", target: "organization", edge_type: "is_executive_in" },
    { source: "person", target: "organization", edge_type: "attended" },
    { source: "person", target: "organization", edge_type: "is_founder_of" },
    { source: "person", target: "organization", edge_type: "is_advisor_in" },
    { source: "person", target: "organization", edge_type: "is_employee_in" },
    {
      source: "person",
      target: "organization",
      edge_type: "is_board_member_in",
    },
    {
      source: "compound",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "vaccine",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "target",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "scientific_concept",
      target: "organization",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "person", target: "organization", edge_type: "is_executive_in" },
    { source: "person", target: "organization", edge_type: "attended" },
    { source: "person", target: "organization", edge_type: "is_founder_of" },
    { source: "person", target: "organization", edge_type: "is_advisor_in" },
    { source: "person", target: "organization", edge_type: "is_employee_in" },
    {
      source: "person",
      target: "organization",
      edge_type: "is_board_member_in",
    },
    {
      source: "scientific_paper",
      target: "scientific_concept",
      edge_type: "is_mentioned_in",
    },
    {
      source: "target",
      target: "scientific_concept",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "scientific_concept",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "scientific_concept",
      edge_type: "is_associated_with",
    },
    { source: "organization", target: "funding_round", edge_type: "raised" },
    {
      source: "organization",
      target: "funding_round",
      edge_type: "participated_in",
    },
    { source: "person", target: "funding_round", edge_type: "participated_in" },
    { source: "organization", target: "funding_round", edge_type: "raised" },
    {
      source: "organization",
      target: "funding_round",
      edge_type: "participated_in",
    },
    {
      source: "compound",
      target: "scientific_paper",
      edge_type: "is_mentioned_in",
    },
    {
      source: "target",
      target: "scientific_paper",
      edge_type: "is_mentioned_in",
    },
    {
      source: "vaccine",
      target: "scientific_paper",
      edge_type: "is_mentioned_in",
    },
    { source: "person", target: "scientific_paper", edge_type: "is_author_of" },
    { source: "target", target: "compound", edge_type: "is_associated_with" },
    { source: "drug", target: "compound", edge_type: "is_ingredient_of" },
    {
      source: "organization",
      target: "compound",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "compound",
      edge_type: "is_associated_with",
    },
    { source: "vaccine", target: "target", edge_type: "is_associated_with" },
    { source: "target", target: "target", edge_type: "is_associated_with" },
    {
      source: "organization",
      target: "target",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "target",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "vaccine",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "vaccine",
      edge_type: "is_associated_with",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_sub_organization_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "organization", target: "organization", edge_type: "acquired" },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_sub_organization_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    { source: "organization", target: "organization", edge_type: "acquired" },
    { source: "person", target: "organization", edge_type: "is_executive_in" },
    { source: "person", target: "organization", edge_type: "attended" },
    { source: "person", target: "organization", edge_type: "is_founder_of" },
    { source: "person", target: "organization", edge_type: "is_advisor_in" },
    { source: "person", target: "organization", edge_type: "is_employee_in" },
    {
      source: "person",
      target: "organization",
      edge_type: "is_board_member_in",
    },
    { source: "organization", target: "person", edge_type: "is_executive_in" },
    { source: "organization", target: "person", edge_type: "attended" },
    { source: "organization", target: "person", edge_type: "is_founder_of" },
    { source: "organization", target: "person", edge_type: "is_advisor_in" },
    { source: "organization", target: "person", edge_type: "is_employee_in" },
    {
      source: "organization",
      target: "person",
      edge_type: "is_board_member_in",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_sub_organization_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_parent_of",
    },
    {
      source: "organization",
      target: "organization",
      edge_type: "is_similar_to",
    },
    { source: "organization", target: "organization", edge_type: "acquired" },
  ],
  vertices: [
    "non_profit_organization",
    "patent",
    "disease",
    "educational_institution",
    "government_organization",
    "scientific_concept",
    "funding_round",
    "scientific_paper",
    "compound",
    "drug",
    "target",
    "vaccine",
    "fund",
    "person",
    "company",
  ],
  maping: {
    organization: [
      "company",
      "fund",
      "non_profit_organization",
      "educational_institution",
      "government_organization",
    ],
  },
};
module.exports = {
  graph_rev,
};
